title: Working with Environment Variables
slug: lab-3
short_description: Learn how to create and use environment variables in your scripts.
lab_environment: vscode
lab_image_url: cloudlearning.azurecr.io/tr-code-server:latest
